import Sidebar from "../components/Header_buttons"

function NotFound() {
    return (
        <div>
        <Sidebar/>
        <h1 style={{color: 'white',
            marginLeft: 100
        }}>404 Not Found</h1>
        <p style={{color: 'white',
            marginLeft: 100
        }}>The page you're looking for doesn't exist!</p>
    </div>
    // <>
    //   <Head>
    //     <title>Bootstrap w/ React</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Container as="main" className="py-4 px-3 mx-auto">
    //     <Header />

    //     <h1>Build Bootstrap with React</h1>

    //     <ExampleComponents />

    //     <hr className="col-1 my-5 mx-0" />

    //     <AppGuides />
    //     <Footer />
    //   </Container>
    // </>
    );
}

export default NotFound